### PR TITLE
BFP: Port read/write examples to bfp.js library

### LINKED ISSUE #3: BFP: Port read/write examples to bfp.js library
The scope of this task is to port the BFP read and write examples as methods to the bfp.js library. Submit a PR to add this functionality, including tests.

The PR should include 100% unit test coverage.

It would also be good to add two e2e tests as part of this task. One for reading data from the blockchain, and one for writing data. Create a test/e2e directory and put those scripts there.

### PR DESCRIPTION
**Pull request by theRealBitcoinClub**
Opening the PR to be able to assign it to the issue.

### CODE REVIEW

**Comment by christroutner** [comment]
I tagged this PR with **[WIF]** to signal a Work In Progress. When this PR is ready for code review, remove the [WIF] tag from the title.

**Comment by theRealBitcoinClub** [comment]
@christroutner still work in progress, but I would strongly recommend that we have a short chat about the sections marked as //TODO inside the code base (or you can check the code and comment inline next to the //TODO tags)

Several questions came up about the specification of the implementation

I am also running into some error messages (Utillib & Stubbing) that I do not understand, would probably help a lot if you would look at these for just a few seconds.

**Comment by theRealBitcoinClub** [comment]
You can also just run npm test and then you will see an error message coming up as the first log output (while all the tests are running green anyway) I do not understand why the tests are running green even as the compiler throws some error.

**Review by christroutner — APPROVED** [review]

**Comment by christroutner** [comment]
:tada: This PR is included in version 1.0.1 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by christroutner** [comment]
303 PSF tokens awarded. TXID:
c5a471ae4ec7976fc5d082cf9c4982e7393fb59c80235ff93755944890bb1e4a

**Pull request merged**
